# Library:
# python version 3.8.5
# pandas version 0.25.3
# mysql-connector-python version 8.0.33
# ipython-sql version 0.4.1
# sqlalchemy version 2.0.13
# sqlite version 3.33.0

In [ ]:
!pip install mysql-connector-python
!pip install ipython-sql

In [11]:
import mysql.connector as connection
import pandas as pd

def sql_query(query):
    try:
        mydb = connection.connect(host="ckhos.go.th", database = 'dhdc',user="root", password="mthpw01",use_pure=True)       
        result_dataFrame = pd.read_sql(query,mydb)
        mydb.close() #close the connection
        return result_dataFrame
    except Exception as e:
        mydb.close()
        print(str(e))

In [12]:
coc_hdc = pd.read_csv('coc_25660508_utf.csv',encoding="utf-8", dtype = str)
coc_hdc

,#,รหัสสถานบริการHOSCODE,ชื่อสถานบริการHOSNAME,ทะเบียนบุคคลPID,เลขที่บัตรประชาชนCID,ชื่อNAME,นามสกุลLNAME,เพศSEX,วันเกิดBIRTH,ที่อยู่ADDRESS,รหัสตามมหาดไทยVHID,สัญชาติNATION,TYPEAREA,DISCHARGE,อายุ,RESULT
0,34,06676,โรงพยาบาลส่งเสริมสุขภาพตำบลสถาน,3104,357030xxxxx048,ประชวง,วงศ์งาม,1,1953-03-13,86,57030212,099,1,9,69,1B1281
1,61,06676,โรงพยาบาลส่งเสริมสุขภาพตำบลสถาน,9567,343010xxxxx594,ไอ่,โพธิ์พรม,2,1947-08-10,265,57030205,099,1,9,75,1B1282
2,89,06676,โรงพยาบาลส่งเสริมสุขภาพตำบลสถาน,2711,357030xxxxx049,แสงคำ,สถานเดิม,2,1939-03-15,127,57030212,099,1,9,83,1B1281
3,189,06676,โรงพยาบาลส่งเสริมสุขภาพตำบลสถาน,571,357030xxxxx059,สังวาลย์,ยะฝั้น,2,1951-12-11,234,57030201,099,1,9,71,1B1282
4,511,06676,โรงพยาบาลส่งเสริมสุขภาพตำบลสถาน,1674,357030xxxxx318,นิล,เทพยศ,2,1956-11-06,163,57030216,099,1,9,66,1B1281
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,11903,23983,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านทุ่งงิ้ว,4605,357030xxxxx931,มานิต,ทะกัน,1,1958-05-29,57,57030202,099,1,9,64,1B1281
107,11917,23983,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านทุ่งงิ้ว,4706,357030xxxxx659,นา,กันทามูล,2,1934-12-01,85,57030202,099,1,9,88,1B1282
108,11955,23983,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านทุ่งงิ้ว,5095,357030xxxxx910,ทอง,ไวดี,1,1936-12-01,274,57030209,099,1,9,86,1B1282
109,12060,23983,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านทุ่งงิ้ว,5812,357030xxxxx776,ปัน,เนืองนิตย์,2,1932-02-01,5,57030211,099,1,9,90,1B1281
110,12164,23983,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านทุ่งงิ้ว,5999,357050xxxxx551,พรมมา,พรหมต๊ะ,1,1930-04-09,103/1,57030202,099,3,9,92,1B1281

In [ ]:
#print(coc_hdc.dtypes)

In [13]:
coc_hdc['hospid'] = coc_hdc['รหัสสถานบริการHOSCODE'] + coc_hdc['ทะเบียนบุคคลPID']#.astype(str) 
coc_hdc['name'] = coc_hdc['ชื่อNAME'] +' '+ coc_hdc['นามสกุลLNAME']
coc_hdc_left = coc_hdc.loc[:, ['รหัสสถานบริการHOSCODE','ชื่อสถานบริการHOSNAME','name', 'hospid','RESULT']]
coc_hdc_left

,รหัสสถานบริการHOSCODE,ชื่อสถานบริการHOSNAME,name,hospid,RESULT
0,06676,โรงพยาบาลส่งเสริมสุขภาพตำบลสถาน,ประชวง วงศ์งาม,066763104,1B1281
1,06676,โรงพยาบาลส่งเสริมสุขภาพตำบลสถาน,ไอ่ โพธิ์พรม,066769567,1B1282
2,06676,โรงพยาบาลส่งเสริมสุขภาพตำบลสถาน,แสงคำ สถานเดิม,066762711,1B1281
3,06676,โรงพยาบาลส่งเสริมสุขภาพตำบลสถาน,สังวาลย์ ยะฝั้น,06676571,1B1282
4,06676,โรงพยาบาลส่งเสริมสุขภาพตำบลสถาน,นิล เทพยศ,066761674,1B1281
...,...,...,...,...,...
106,23983,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านทุ่งงิ้ว,มานิต ทะกัน,239834605,1B1281
107,23983,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านทุ่งงิ้ว,นา กันทามูล,239834706,1B1282
108,23983,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านทุ่งงิ้ว,ทอง ไวดี,239835095,1B1282
109,23983,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านทุ่งงิ้ว,ปัน เนืองนิตย์,239835812,1B1281
110,23983,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านทุ่งงิ้ว,พรมมา พรหมต๊ะ,239835999,1B1281

In [14]:
dental_cid = sql_query( """ 
SELECT
DT.hospid,
DT.CID,
DT.flag_dental 

FROM
(
SELECT DISTINCT   
    CONCAT(person.HOSPCODE, person.PID) AS hospid,
    person.CID,
    case when dental.DATE_SERV = max(dental.DATE_SERV) OVER (PARTITION BY dental.CID) 
             then '1' else '0'
    end AS flag_dental 
    
    from dental    
    
    INNER JOIN provider ON provider.provider = dental.provider AND provider.HOSPCODE = dental.HOSPCODE
    INNER JOIN person ON person.cid = dental.cid 
    
    WHERE 
    
    provider.providertype IN ('02','06')
    AND person.TYPEAREA IN ('1', '3')
    AND dental.PTEETH BETWEEN 0 AND 32
    AND DATE_FORMAT(FROM_DAYS(DATEDIFF('2022-10-01',person.BIRTH)), '%Y')+0 BETWEEN 60 AND 199
    AND IFNULL(dental.PERMANENT_PERMANENT,0) + IFNULL(dental.PERMANENT_PROSTHESIS,0)
    + IFNULL(dental.PROSTHESIS_PROSTHESIS,0) BETWEEN 0 AND 10
    AND (IFNULL(dental.pteeth,0) +IFNULL(dental.PEXTRACT,0)) > 0
    AND dental.DATE_SERV BETWEEN '2022-10-01' AND '2023-09-30'
    AND LENGTH(dental.CID)=13 
    
  )  AS DT

where
DT.flag_dental = '1'
""" )

dental_cid

<ipython-input-11-eb259d99cf72>:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result_dataFrame = pd.read_sql(query,mydb)

           hospid            CID flag_dental
0       066798280  0570389003943           1
1        06678604  0570389004290           1
2        06678556  0570389011725           1
3       066801776  0576789000017           1
4       066813455  2570300002019           1
...           ...            ...         ...
1726  11454110421  8570386000108           1
1727  11454120984  8571384003861           1
1728  11454114624  8577073001128           1
1729  11454016574  8577073001136           1
1730  11454093162  8577073002370           1

[1731 rows x 3 columns]

In [15]:
tb_merge = pd.merge(coc_hdc_left, dental_cid, on=['hospid'], how='left')
tb_merge

,รหัสสถานบริการHOSCODE,ชื่อสถานบริการHOSNAME,name,hospid,RESULT,CID,flag_dental
0,06676,โรงพยาบาลส่งเสริมสุขภาพตำบลสถาน,ประชวง วงศ์งาม,066763104,1B1281,NaN,NaN
1,06676,โรงพยาบาลส่งเสริมสุขภาพตำบลสถาน,ไอ่ โพธิ์พรม,066769567,1B1282,NaN,NaN
2,06676,โรงพยาบาลส่งเสริมสุขภาพตำบลสถาน,แสงคำ สถานเดิม,066762711,1B1281,NaN,NaN
3,06676,โรงพยาบาลส่งเสริมสุขภาพตำบลสถาน,สังวาลย์ ยะฝั้น,06676571,1B1282,NaN,NaN
4,06676,โรงพยาบาลส่งเสริมสุขภาพตำบลสถาน,นิล เทพยศ,066761674,1B1281,NaN,NaN
...,...,...,...,...,...,...,...
106,23983,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านทุ่งงิ้ว,มานิต ทะกัน,239834605,1B1281,NaN,NaN
107,23983,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านทุ่งงิ้ว,นา กันทามูล,239834706,1B1282,NaN,NaN
108,23983,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านทุ่งงิ้ว,ทอง ไวดี,239835095,1B1282,NaN,NaN
109,23983,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านทุ่งงิ้ว,ปัน เนืองนิตย์,239835812,1B1281,NaN,NaN
110,23983,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านทุ่งงิ้ว,พรมมา พรหมต๊ะ,239835999,1B1281,NaN,NaN

In [ ]:
tb_merge.style.hide(axis='index')

In [16]:
from sqlalchemy import create_engine
engine = create_engine('sqlite://', echo = False)

In [17]:
tb_merge.to_sql('COC_Data',
                       con = engine,
                       schema=None,
                       if_exists = 'append')

111

In [18]:
coc2 = pd.read_sql('''
SELECT 
Q1.hospcode,
Q1.cup,
Q1.target,
Q1.exam,
ROUND(((Q1.exam/1.0)/Q1.target)*100, 2) AS percent

FROM
(
SELECT DISTINCT
รหัสสถานบริการHOSCODE AS hospcode,
ชื่อสถานบริการHOSNAME AS cup,
COUNT(DISTINCT hospid) AS target,
COUNT(flag_dental) AS exam

FROM COC_Data

WHERE

RESULT IN('1B1281','1B1282')

GROUP BY hospcode,cup
) AS Q1
''', engine)

target_sum = coc2.target.sum()
dental_sum = coc2.exam.sum()
percent_total = ((dental_sum/target_sum)*100).round(2)
coc2.loc[len(coc2.index)] = ['All', 'Total', target_sum,dental_sum,percent_total]
coc2
#coc2.dtypes

,hospcode,cup,target,exam,percent
0,06676,โรงพยาบาลส่งเสริมสุขภาพตำบลสถาน,7,0,0.00
1,06677,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านน้ำม้า,11,0,0.00
2,06678,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านทุ่งอ่าง ห,1,1,100.00
3,06679,โรงพยาบาลส่งเสริมสุขภาพตำบลครึ่ง,7,2,28.57
4,06680,โรงพยาบาลส่งเสริมสุขภาพตำบลม่วงชุม,3,1,33.33
5,06681,โรงพยาบาลส่งเสริมสุขภาพตำบลบุญเรือง,9,1,11.11
6,06682,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านซ้อเหนือ,3,0,0.00
7,06683,โรงพยาบาลส่งเสริมสุขภาพตำบลห้วยซ้อ,17,0,0.00
8,06684,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านใหม่ดอนแก้ว,3,0,0.00
9,06685,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านเขียะ,9,0,0.00
10,06686,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านดงหลวง,4,0,0.00
11,06687,โรงพยาบาลส่งเสริมสุขภาพตำบลศรีดอนชัย,1,0,0.00
12,06689,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านเมืองกาญจน์,8,1,12.50
13,10436,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านสองพี่น้อง,1,0,0.00
14,11454,โรงพยาบาลสมเด็จพระยุพราชเชียงของ,20,4,20.00
15,15004,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านศรีวิไล,1,0,0.00
16,23983,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านทุ่งงิ้ว,6,0,0.00
17,All,Total,111,10,9.01

In [19]:
coc2.style.hide(axis='index').format({'percent': '{:.2f}'})

In [ ]:
coc2.to_excel(r'D:\selenium\coc_dental_exam.xlsx', header=True,index=False)